# Generated by Django 5.0.6 on 2024-06-06 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigiShelfData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profit_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("processing_fee", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "giftcard_processing_fee",
                    models.DecimalField(decimal_places=2, default=5, max_digits=5),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="last name"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="staff status"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="date joined"),
                ),
                ("device", models.CharField(default="Web", max_length=250)),
                ("phone_number", models.IntegerField(blank=True, null=True)),
                (
                    "country",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                ("email_verified", models.BooleanField(default=False)),
                (
                    "last_login",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="last login"
                    ),
                ),
                ("auth_type", models.CharField(default="email", max_length=100)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.CreateModel(
            name="GiftCardTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.TextField(default=None, unique=True)),
                ("product_name", models.CharField(default=None, max_length=250)),
                ("product_id", models.CharField(default=None, max_length=250)),
                (
                    "receiver_currency_code",
                    models.CharField(default=None, max_length=250),
                ),
                (
                    "recipient_amount",
                    models.DecimalField(decimal_places=2, default="3.4", max_digits=9),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=9)),
                ("country", models.CharField(default=None, max_length=250)),
                ("email", models.EmailField(default=None, max_length=254)),
                ("user_type", models.CharField(default="guest", max_length=250)),
                ("payment_method", models.CharField(default="visa", max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="giftcard_transaction",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=250)),
                ("status", models.CharField(max_length=250)),
                ("transaction", models.CharField(max_length=250)),
                ("trxref", models.CharField(max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "GiftCardTransaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_details",
                        to="api.giftcardtransaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TopupTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_type", models.CharField(default="guest", max_length=200)),
                ("operator", models.CharField(default=None, max_length=200)),
                ("amount_in_usd", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "amount_local_currency",
                    models.DecimalField(decimal_places=2, max_digits=9),
                ),
                ("processing_fee", models.DecimalField(decimal_places=2, max_digits=9)),
                ("payment_method", models.CharField(default=None, max_length=200)),
                (
                    "phone_number",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default=None, max_length=254, null=True
                    ),
                ),
                ("country", models.CharField(default=None, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transactionId", models.IntegerField(default=None)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=9)),
                ("discount", models.DecimalField(decimal_places=2, max_digits=9)),
                ("currencyCode", models.CharField(max_length=250)),
                ("fee", models.DecimalField(decimal_places=2, max_digits=9)),
                ("status", models.CharField(default=None)),
                ("product", models.TextField(default=None)),
                ("transaction_created_at", models.DateTimeField(default=None)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "GiftCardTransaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_details_completed",
                        to="api.giftcardtransaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserDeviceGiftCardPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(default=None, max_length=250)),
                (
                    "GiftCardTransaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_details_user_device",
                        to="api.giftcardtransaction",
                    ),
                ),
            ],
        ),
    ]
