# Generated by Django 5.0.6 on 2024-05-17 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("api", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("social_django", "0015_rename_extra_data_new_usersocialauth_extra_data"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomUser",
            new_name="Account",
        ),
    ]
