# Generated by Django 5.0.6 on 2024-06-06 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionproduct",
            name="transaction_created_at",
        ),
    ]
