# Generated by Django 5.0.6 on 2024-06-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_transactionproduct_transaction_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionproduct",
            name="transaction_created_at",
            field=models.DateTimeField(default=None),
        ),
    ]
