# Generated by Django 5.0.6 on 2024-05-29 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_digishelfdata_processing_fee"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopupTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_type", models.CharField(default="guest", max_length=200)),
                ("operator", models.CharField(default=None, max_length=200)),
                ("amount_in_usd", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "amount_local_currency",
                    models.DecimalField(decimal_places=2, max_digits=9),
                ),
                ("processing_fee", models.DecimalField(decimal_places=2, max_digits=9)),
                ("payment_method", models.CharField(default=None, max_length=200)),
                (
                    "phone_number",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default=None, max_length=254, null=True
                    ),
                ),
                ("country", models.CharField(default=None, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
