# Generated by Django 5.0.6 on 2024-05-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_customuser_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="country",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="phone_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
