# Generated by Django 5.0.6 on 2024-06-06 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_transactionproduct_transaction_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardRedeemCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("redeem_card_number", models.CharField(max_length=250)),
                ("redeem_card_pin", models.CharField(max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "TransactionProduct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_details_completed",
                        to="api.transactionproduct",
                    ),
                ),
            ],
        ),
    ]
