# Generated by Django 5.0.6 on 2024-06-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_transactionproduct_redeem_card_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionproduct",
            name="redeem_data",
            field=models.TextField(default=None, null=True),
        ),
    ]
