# Generated by Django 5.0.6 on 2024-05-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_account_country_alter_account_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="last name"
            ),
        ),
    ]
