# Generated by Django 5.0.6 on 2024-05-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_account_first_name_alter_account_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="auth_type",
            field=models.CharField(default="email", max_length=100),
        ),
    ]
