# Generated by Django 5.0.6 on 2024-06-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_transactionproduct_redeem_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionproduct",
            name="redeem_data",
            field=models.TextField(default=None),
        ),
    ]
