# Generated by Django 5.0.6 on 2024-06-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_errorlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="errorlog",
            name="email",
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name="errorlog",
            name="resolve",
            field=models.BooleanField(default=False),
        ),
    ]
