# Generated by Django 5.0.6 on 2024-06-24 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_transactionproduct_redeem_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productName", models.CharField(default=None, max_length=250)),
                ("productId", models.IntegerField(default=None)),
                ("quantity", models.IntegerField(default=None)),
                (
                    "recipientAmount",
                    models.DecimalField(decimal_places=2, max_digits=9),
                ),
                ("recipientCurrency", models.CharField(default=None)),
                ("AmountToPay", models.DecimalField(decimal_places=2, max_digits=9)),
                ("currencyToPayIn", models.CharField(default=None, max_length=10)),
                ("img", models.CharField(default=None, max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
