# Generated by Django 5.0.6 on 2024-06-08 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_errorlog_email_errorlog_resolve"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="errorlog",
            name="email",
        ),
    ]
