# Generated by Django 5.0.6 on 2024-06-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="processing_fee",
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=9),
        ),
    ]
