# Generated by Django 5.0.6 on 2024-07-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_cart_processing_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="topuptransaction",
            name="Receiver_country",
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name="topuptransaction",
            name="receiver_amount",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=9),
        ),
    ]
