# Generated by Django 5.0.6 on 2024-06-12 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_errorlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="giftcardtransaction",
            name="product_id",
        ),
        migrations.RemoveField(
            model_name="giftcardtransaction",
            name="product_name",
        ),
        migrations.RemoveField(
            model_name="giftcardtransaction",
            name="receiver_currency_code",
        ),
        migrations.RemoveField(
            model_name="giftcardtransaction",
            name="recipient_amount",
        ),
        migrations.CreateModel(
            name="GiftCardTransactionOrderProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productName", models.CharField(default=None, max_length=250)),
                ("productId", models.IntegerField(default=None)),
                ("quantity", models.IntegerField(default=None)),
                (
                    "recipientAmount",
                    models.DecimalField(decimal_places=2, max_digits=9),
                ),
                ("recipientCurrency", models.CharField(default=None)),
                ("amountToPay", models.DecimalField(decimal_places=2, max_digits=9)),
                ("currencyToPayIn", models.CharField(default=None, max_length=10)),
                ("img", models.CharField(default=None, max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "GiftCardTransaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_order_product",
                        to="api.giftcardtransaction",
                    ),
                ),
            ],
        ),
    ]
