# Generated by Django 5.0.6 on 2024-07-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_topuptransaction_receiver_country_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topuptransaction",
            old_name="Receiver_country",
            new_name="receiver_country",
        ),
        migrations.RenameField(
            model_name="topuptransaction",
            old_name="amount_in_usd",
            new_name="total_paid",
        ),
        migrations.RemoveField(
            model_name="topuptransaction",
            name="amount_local_currency",
        ),
        migrations.AddField(
            model_name="topuptransaction",
            name="paystack_very_transaction",
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="topuptransaction",
            name="receiver_currency_code",
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name="topuptransaction",
            name="reference",
            field=models.CharField(default=False, max_length=14, unique=True),
        ),
        migrations.AddField(
            model_name="topuptransaction",
            name="reloader_transaction",
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="topuptransaction",
            name="sender_country",
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name="topuptransaction",
            name="sender_currency",
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name="topuptransaction",
            name="status",
            field=models.CharField(default=None, max_length=250),
        ),
    ]
