# Generated by Django 5.0.6 on 2024-06-12 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_remove_giftcardtransaction_product_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="giftcardtransactionorderproduct",
            old_name="amountToPay",
            new_name="AmountToPay",
        ),
    ]
