# Generated by Django 5.0.6 on 2024-07-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0010_rename_receiver_country_topuptransaction_receiver_country_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="topuptransaction",
            name="phone_number",
            field=models.CharField(default=None, max_length=250),
        ),
    ]
