# Generated by Django 5.0.6 on 2024-06-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_rename_amounttopay_giftcardtransactionorderproduct_amounttopay"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionproduct",
            name="redeem_card_number",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="transactionproduct",
            name="redeem_card_pin",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
