# Generated by Django 5.0.6 on 2024-07-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_topuptransaction_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=250)),
                ("email", models.EmailField(default=None, max_length=254)),
                ("message", models.TextField(default=None)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
