# Generated by Django 5.2.13 on 2026-04-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_account_deleted_account_suspended'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digishelfdata',
            options={'verbose_name': 'DigiShelf Configuration', 'verbose_name_plural': 'DigiShelf Configuration'},
        ),
        migrations.AlterField(
            model_name='digishelfdata',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='digishelfdata',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
    ]
