# Generated by Django 5.2.13 on 2026-05-07 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_contact_admin_reply_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=120)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('page_path', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('page_title', models.CharField(blank=True, max_length=250, null=True)),
                ('product_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('product_name', models.CharField(blank=True, max_length=250, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('cart_item_count', models.PositiveIntegerField(default=0)),
                ('cart_total_quantity', models.PositiveIntegerField(default=0)),
                ('cart_total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
