# Generated by Django 5.2.13 on 2026-10-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_blockedurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='digishelfdata',
            name='include_restricted_in_sitemap',
            field=models.BooleanField(default=False),
        ),
    ]
